table 'Estado SI'
	lineageTag: d0032e1b-15d0-4795-ab8e-0a65979b40d5

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: ef4ea65c-d44e-4754-b55c-4e6fb62d509f
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Codigo
		dataType: string
		isHidden
		lineageTag: 9d892168-de26-4870-9f7b-979352cd091c
		summarizeBy: none
		sourceColumn: Codigo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		isHidden
		lineageTag: d75ba1ac-3245-4126-8bed-3d3cc6b55a2b
		summarizeBy: none
		sourceColumn: Nombre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a1b6ff31-2a39-464b-afbf-536fa0e9eb7d
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	partition 'Estado SI' = m
		mode: import
		source = ```
				let
				   
				    Origen = SharePoint.Files("https://aranciodata.sharepoint.com/sites/Novaon/", [ApiVersion = 15]),
				    #"Filas filtradasf" = Table.SelectRows(Origen, each Text.StartsWith([Folder Path], "https://aranciodata.sharepoint.com/sites/Novaon/Documentos compartidos/Estados Financieros/")),
				    #"Filas filtradas3" = Table.SelectRows(#"Filas filtradasf", each not Text.StartsWith([Name], "~$")),
				    #"Filas filtradas" = Table.SelectRows(#"Filas filtradas3", each Text.StartsWith([Folder Path], "https://aranciodata.sharepoint.com/sites/Novaon/Documentos compartidos/Estados Financieros/")),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [Extension] = ".xlsx"),
				    #"Texto extraído entre delimitadores" = Table.TransformColumns(#"Filas filtradas1", {{"Folder Path", each Text.BetweenDelimiters(_, "/", "/", {0, RelativePosition.FromEnd}, {0, RelativePosition.FromEnd}), type text}}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Texto extraído entre delimitadores",{"Folder Path", "Content"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "Personalizado", each Excel.Workbook([Content])),
				    #"Se expandió Personalizado" = Table.ExpandTableColumn(#"Personalizada agregada", "Personalizado", {"Name", "Data", "Item", "Kind", "Hidden"}, {"Name", "Data", "Item", "Kind", "Hidden"}),
				    #"Filas filtradas2" = Table.SelectRows(#"Se expandió Personalizado", each [Kind] = "Sheet"),
				    #"Otras columnas quitadas1" = Table.SelectColumns(#"Filas filtradas2",{"Folder Path", "Data"}),
				    #"Función personalizada invocada" = Table.AddColumn(#"Otras columnas quitadas1", "Función", each Función([Data])),
				    #"Otras columnas quitadas2" = Table.SelectColumns(#"Función personalizada invocada",{"Folder Path", "Función"}),
				    #"Se expandió Función" = Table.ExpandTableColumn(#"Otras columnas quitadas2", "Función", {"Column1", "Column2", "Atributo", "Valor"}, {"Column1", "Column2", "Atributo", "Valor"}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Se expandió Función", "Personalizado", each 1),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada1",{"Personalizado", "Atributo", "Folder Path", "Column1", "Column2", "Valor"}),
				    #"Columnas combinadas" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas reordenadas", {{"Personalizado", type text}}, "es-EC"),{"Personalizado", "Atributo", "Folder Path"},Combiner.CombineTextByDelimiter("/", QuoteStyle.None),"Fecha"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas combinadas",{{"Column1", "Codigo"}, {"Column2", "Nombre"}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Valor", type number}, {"Codigo", type text}, {"Nombre", type text}, {"Fecha", type date}})
				in
				    #"Tipo cambiado"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

